Repository UoA-Discords/uoa-discords-website, pull requests merged in 2022-04, with the labels that each got.

#11 Discord oauth
  .gitignore
  package.json
  src/App.tsx
  src/api/api.ts
  src/api/index.ts
  src/components/AccountButton/AccountButton.css
  src/components/AccountButton/AccountButton.tsx
  src/components/AccountButton/index.tsx
  src/components/AccountPage/AccountPage.css
  src/components/AccountPage/AccountPage.tsx
  src/components/AccountPage/index.tsx
  src/components/AddGuild/AddGuild.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/index.tsx
  src/components/LoginRedirect/LoginRedirect.tsx
  src/components/LoginRedirect/index.tsx
  src/components/MainPage.tsx
  src/config.json
  src/hooks/useDiscordAccess.ts
  src/hooks/useUser.ts
  src/images/discordIcon.svg
  src/index.tsx
  src/types/Config.ts
  yarn-error.log
  yarn.lock
Labels: enhancement, do not merge

#12 Apply Forms
  src/App.tsx
  src/components/AccountPage/AccountPage.css
  src/components/AccountPage/AccountPage.tsx
  src/components/AddGuild/AddGuild.tsx
  src/components/AddGuild/AddGuildCard.css
  src/components/AddGuild/AddGuildCard.tsx
  src/components/AddGuild/SelectedGuildModal.tsx
  src/components/AddGuild/index.tsx
  src/components/Auth/Auth.tsx
  src/components/HomeButton/HomeButton.css
  src/components/HomeButton/HomeButton.tsx
  src/components/HomeButton/index.tsx
  src/types/ExtendedGuild.ts
  yarn.lock
Labels: enhancement

#13 UI Overhaul
  src/App.css
  src/App.tsx
  src/api/api.ts
  src/components/AccountButton/AccountButton.css
  src/components/AccountButton/AccountButton.tsx
  src/components/AccountPage/AccountPage.css
  src/components/AccountPage/AccountPage.tsx
  src/components/AccountPage/FullAccountPage.css
  src/components/AccountPage/FullAccountPage.tsx
  src/components/AccountPage/LoadingAccountPage.tsx
  src/components/AddGuild/AddGuild.tsx
  src/components/AddGuild/AddGuildCard.css
  src/components/AddGuild/AddGuildCard.tsx
  src/components/AddGuild/SelectedGuildModal.tsx
  src/components/AddGuild/index.tsx
  src/components/Apply/Apply.tsx
  src/components/Apply/index.tsx
  src/components/Auth/Auth.tsx
  src/components/HomeButton/HomeButton.css
  src/components/HomeButton/HomeButton.tsx
  src/components/HomeButton/index.tsx
  src/components/LoginRedirect/LoginRedirect.tsx
  src/components/MainPage.tsx
  src/components/NotFound/NotFound.tsx
  src/components/NotFound/index.tsx
  src/components/ServerCard.tsx
  src/components/ServerGallery.tsx
  src/components/Title/Title.tsx
  src/components/Title/index.tsx
  src/hooks/useDiscordAccess.ts
  src/hooks/useDiscordUser.ts
  src/images/adios.png
  src/sampleData.ts
  src/types/APIResponse.ts
Labels: documentation, enhancement

#14 Adios
  src/components/LoginRedirect/LoginRedirect.tsx
  src/images/adios.png
Labels: enhancement

#15 Package updates
  .github/workflows/node.js.yml
  package.json
  src/App.test.tsx
  src/App.tsx
  src/api/api.ts
  src/api/index.ts
  src/components/AccountButton/AccountButton.css
  src/components/AccountButton/AccountButton.tsx
  src/components/AccountPage/AccountPage.tsx
  src/components/AccountPage/FullAccountPage.tsx
  src/components/AccountPage/LoadingAccountPage.tsx
  src/components/Apply/Apply.tsx
  src/components/Auth/Auth.tsx
  src/components/LoginRedirect/LoginRedirect.tsx
  src/components/NotFound/NotFound.tsx
  src/components/ServerGallery.tsx
  src/components/Title/Title.tsx
  src/hooks/useDiscordAccess.ts
  src/hooks/useDiscordUser.ts
  src/index.tsx
  src/types/APIResponse.ts
  src/types/ExtendedGuild.ts
  yarn.lock
Labels: documentation

#16 Apply form
  package.json
  src/api/Server.ts
  src/api/api.ts
  src/components/AccountPage/FullAccountPage.tsx
  src/components/AddServerPage/AddServerPage.tsx
  src/components/AddServerPage/index.tsx
  src/components/Auth/Auth.tsx
  src/hooks/useDebounce.ts
  yarn.lock
Labels: enhancement

#20 Apply Page
  src/api/Server.ts
  src/components/AccountButton/AccountButton.tsx
  src/components/AccountPage/FullAccountPage.tsx
  src/components/AddServerPage/AddServerPage.tsx
  src/components/AddServerPage/ValidationStep.tsx
  src/components/AddServerPage/steps.tsx
  src/components/LightTooltip/LightTooltip.tsx
  src/components/LightTooltip/index.tsx
  src/components/TagSelector/TagSelector.tsx
  src/components/TagSelector/index.tsx
  src/hooks/useBadges.tsx
  yarn.lock
Labels: enhancement

#21 Manage Applications Page
  src/App.css
  src/App.tsx
  src/api/Server.ts
  src/components/AccountPage/FullAccountPage.tsx
  src/components/ApplicationsPage/ApplicationRow.tsx
  src/components/ApplicationsPage/ApplicationsPage.tsx
  src/components/ApplicationsPage/index.tsx
  src/components/Apply/Apply.tsx
  src/components/Apply/index.tsx
  src/components/Auth/Auth.tsx
  src/components/TagSelector/TagSelector.tsx
  src/components/UserCard/UserCard.tsx
  src/components/UserCard/index.tsx
  src/types/ServerApplication.ts
Labels: enhancement

#22 Server Listing
  src/App.tsx
  src/api/Server.ts
  src/components/MainPage.tsx
  src/components/ServerCard.tsx
  src/components/ServerGallery.tsx
  src/sampleData.ts
Labels: enhancement, help wanted

#23 Clickable servers
  package.json
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/api/Server.ts
  src/components/AddServerPage/AddServerPage.tsx
  src/components/AddServerPage/steps.tsx
  src/components/ApplicationsPage/ApplicationRow.tsx
  src/components/ApplicationsPage/ApplicationsPage.tsx
  src/components/MainPage.tsx
  src/components/SelectedGuild/SelectedGuild.tsx
  src/components/SelectedGuild/index.tsx
  src/components/ServerCard.tsx
  src/components/ServerGallery.tsx
  src/components/TagSelector/TagSelector.tsx
  src/components/Title/Title.tsx
  src/index.tsx
  src/redux/slices/guildManager/guildManager.slice.ts
  src/redux/slices/guildManager/index.ts
  src/redux/slices/main/index.ts
  src/redux/slices/main/main.slice.ts
  src/redux/store.ts
  src/types/LoadedGuild.ts
  src/types/ServerApplication.ts
  yarn.lock
Labels: enhancement

#24 Added metadata tags and favicon
  public/banner1.png
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
Labels: enhancement

#25 Colour
  public/index.html
Labels: enhancement

#26 Fix ratelimiting
  package.json
  src/api/Server.ts
  src/components/MainPage.tsx
  src/components/SelectedGuild/SelectedGuild.tsx
  src/components/ServerCard.tsx
  src/redux/slices/guildManager/guildManager.slice.ts
  src/redux/slices/main/main.slice.ts
  src/types/LoadedGuild.ts
  yarn.lock
Labels: bug, enhancement

#28 Cleanup
  .gitignore
  README.md
  package.json
  public/index.html
  src/components/AccountButton/AccountButton.tsx
  src/components/AccountPage/FullAccountPage.tsx
  src/components/ServerGallery.tsx
  src/components/UserCard/UserCard.tsx
  src/helpers/getDiscordIcon.ts
  yarn.lock
Labels: documentation, enhancement

#30 Like Buttons
  package.json
  src/App.tsx
  src/api/Server.ts
  src/components/ServerCard.tsx
  src/redux/slices/guildManager/guildManager.slice.ts
  src/redux/slices/user/index.ts
  src/redux/slices/user/user.slice.ts
  src/redux/store.ts
  yarn.lock
Labels: enhancement
